In [5]:
import numpy as np

In [5]:
# a partir de uma lista ou tupla

lista = [1, 2, 3, 4]

tupla = (1, 2, 3, 4)

array_a_partir_de_lista = np.array(lista)

array_a_partir_de_tupla = np.array(tupla)

print(array_a_partir_de_lista)

[1 2 3 4]


In [6]:
# usando o range

array_simples = np.arange(10)

array_sequencial = np.arange(10, 100, 10)

array_simples, array_sequencial

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [9]:
# criando arrays de zeros ou ums

vetor_zero = np.zeros(5)
vetor_um = np.ones(5)

vetor_zero, vetor_um

(array([0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1.]))

In [11]:
# criando vetores aleatórios

vetor_aleatorio_entre_0_1 = np.random.rand(3, 2) # três vetores de tamanho "2"
vetor_aleatorio_inteiro = np.random.randint(low = 0, high = 10, size = 3) 
vetor_aleatorio_com_negativos = np.random.uniform(-2, 2, 3) # intervalo entre -2 e 2 ; tamanho 3

print(vetor_aleatorio_entre_0_1)
print(vetor_aleatorio_inteiro)
print(vetor_aleatorio_com_negativos)

[[0.73510969 0.36361787]
 [0.64945503 0.78922917]
 [0.0056494  0.50561822]]
[7 3 5]
[-0.42854496 -1.94396972 -1.11497855]


In [12]:
# criando arrays bi ou tridimensionais

lista1 = [1, 2, 3]
lista2 = [4, 5, 6]
lista3 = [7, 8, 9]

array2d = np.array([lista1, lista2])

array3d = np.array([lista1, lista2, lista3])

array2d, array3d

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [13]:
# criando matrizes

matriz = np.matrix([[20, 30], [90, 80]])

matriz

matrix([[20, 30],
        [90, 80]])

In [14]:
# listas x numpy

lista_1 = [1, 1, 1, 1]
lista_2 = [1, 1, 1, 1]

print(lista_1 + lista_2)
print(np.array(lista_1) + np.array(lista_2))

[1, 1, 1, 1, 1, 1, 1, 1]
[2 2 2 2]


In [3]:
# teste lista x numpy

import timeit

# listas

tempo_listas = timeit.timeit('''X = range(1000); Y = range(1000); [X[i] + Y[i] for i in range(len(X))]''', number = 10000)

# vetores

tempo_vetor = timeit.timeit('''X = np.arange(1000); Y = np.arange(1000); X + Y''', number = 10000, setup = "import numpy as np")

print(tempo_listas, tempo_vetor)
print(f'Os vetores são {tempo_listas/ tempo_vetor} vezes mais rápidos.')
# print ("Numpy nesse caso é " + str(t1/t2) + "mais rápido")


0.8325431660050526 0.011586374952457845
Os vetores são 71.85536195930231 vezes mais rápidos.


In [17]:
'''
Exercício 30: Peça pro usuário inputar a cotação de 3 ações. Crie um array de cotações.
Exercício 31: Peça pro usuário digitar dois números no programa e crie um arrange sequencial entre esses números
Exercício 32: Crie um programa que gere números aleatórios inteiros entre 0 e 60 e devolva 6 números da mega sena pro
usuário. Depois, exiba uma probabilidade aleatória de o usuário sair vencedor. garanta que ejam 6 números diferentes!
'''

In [7]:
acao1 = float(input("Digite a cotação da primeira ação: "))
acao2 = float(input("Digite a cotação da segunda ação: "))
acao3 = float(input("Digite a cotação da terceira ação: "))

array = np.array([acao1, acao2, acao3])

print(array)

Digite a cotação da primeira ação: 20
Digite a cotação da segunda ação: 30
Digite a cotação da terceira ação: 40
[20. 30. 40.]


In [8]:
inicio_sequencia = float(input("Digite o primeiro número: "))
final_sequencia = float(input("Digite o segundo número: "))

sequencia = np.arange(inicio_sequencia, final_sequencia)

sequencia

Digite o primeiro número: 10
Digite o segundo número: 20


array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [13]:
lista_numeros = []

lista_numeros.append(np.random.randint(0, 60, 1)[0])

while len(lista_numeros) < 6:
    
    mega_sena = np.random.randint(0, 60, 1)
    
    if mega_sena not in lista_numeros:
        
        lista_numeros.append(mega_sena[0])
        
probabilidade_vitoria = np.random.rand(1)[0]

print(f'Seguem os números da mega sena: {lista_numeros}. A probabilidade de vitória é de {probabilidade_vitoria}')

Seguem os números da mega sena: [15, 2, 14, 39, 13, 28]. A probabilidade de vitória é de 0.834236293728925
