In [1]:
import numpy as np

In [8]:
# juntar dois arrays

array1 = np.arange(20,25)
array2 = np.arange(15)

array_completo = np.concatenate([array1, array2])

print(array_completo)

[20 21 22 23 24  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [9]:
# separando em dois arrays

array_separado1, array_separado2 = np.split(array_completo,[5])

print(array_separado1)
print(array_separado2)

[20 21 22 23 24]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [10]:
# colocar novos dados em um array

# [20 21 22 23 24  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

array_completo = np.append(array_completo, 2000)

array_completo = np.insert(array_completo, 3, 3000)

print(array_completo)

[  20   21   22 3000   23   24    0    1    2    3    4    5    6    7
    8    9   10   11   12   13   14 2000]


In [11]:
# deletar dados de um array

array_completo = np.delete(array_completo, -1)

print(array_completo)

[  20   21   22 3000   23   24    0    1    2    3    4    5    6    7
    8    9   10   11   12   13   14]


In [12]:
# reshape

array_3x3 = np.arange(9).reshape(3, 3) #isso aqui é útil na hora de fazer regressão linear

print(array_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
# trocando números dentro de uma condição

array_inicial = np.array([4, 4, 4, 4, 7, 6, 5, 32, 13, 2, 32, 675, 74, 465])

# como trocar todos os números menores que 40 por 0?

array_booleano = (array_inicial < 40)

print(array_booleano)

array_inicial[array_booleano] = 0

print(array_inicial)

[ True  True  True  True  True  True  True  True  True  True  True False
 False False]
[  0   0   0   0   0   0   0   0   0   0   0 675  74 465]


In [14]:
# como ordenar objetos dentro de uma lista?

array_desordenado = np.array([23109, 2309, 349, 20, 3, 5, 12490])

array_crescente = np.sort(array_desordenado)
array_decrescente = -np.sort(-array_desordenado)

print(array_crescente, array_decrescente)

[    3     5    20   349  2309 12490 23109] [23109 12490  2309   349    20     5     3]


In [ ]:
# exercício 34: peça ao usuário digitar o lucro da Petrobras, Vale e Weg. Mostre os lucros em ordem do maior pro menor.

In [ ]:
empresas = np.array(["Weg", "Vale", "Petrobras"])

array_lucros = np.array([])

for empresa in empresas:
    
    lucro = float(input(f'Digite o lucro da {empresa}:'))
    array_lucros = np.append(array_lucros, lucro)

array_lucros = -np.sort(-array_lucros)

print(f'Lucro das empresas, do maior pro menor: {array_lucros}')